CREATE TABLE IF NOT EXISTS devices (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    ip_address TEXT UNIQUE NOT NULL,
    mac_address TEXT UNIQUE NOT NULL,
    kind TEXT NOT NULL,
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
