CREATE TABLE IF NOT EXISTS coupons (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(20) UNIQUE NOT NULL,
    allowed_time INTEGER UNSIGNED DEFAULT 60,
    allowed_devices INTEGER UNSIGNED DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
